spring.application.name=dscommerce

spring.profiles.active=test

#Essa propriedade faz com que a sessão JPA seja encerrada antes de voltar para a camada controller(camada web), deixando as transações apenas no service.
#Desta forma, para funcionar, devemos colocar o @Transactional nos services.
spring.jpa.open-in-view=false