spring.application.name=dscommerce

spring.profiles.active=test

#Essa propriedade faz com que a sessão JPA seja encerrada antes de voltar para a camada controller(camada web), deixando as transações apenas no service.
#Desta forma, para funcionar, devemos colocar o @Transactional nos services.
spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}